http:
  server_host: 127.0.0.1
  server_port: 8123
  use_x_forwarded_for: true
  trusted_proxies: 127.0.0.1

logger:
  # default: info
  logs:
    homeassistant.components.automation: info
    homeassistant.components.script: info
    homeassistant.components.system_log: debug
    custom_components.multicast_exec: debug

sun:
# Enable Apple TV
zeroconf:
dhcp:
# Enable mobile application
mobile_app:
# Enable state history
history:
multicast_exec:

resources:
  - url: "/local/slider-entity-row/slider-entity-row.js"
    type: js

script:
  first_floor_low_lights_on:
    alias: First Floor Low Lights On
    description: Turn Low Lights On
    mode: queued
    sequence:
      - action: multicast_exec.set
        data:
          target_state: true
          entity_id:
            - switch.living_room_corner_lamp
            - switch.living_room_bookshelf_lamp
            - switch.under_cabinet_lights
            - light.island_lights

  first_floor_low_lights_toggle:
    alias: First Floor Low Lights Toggle
    description: Toggle Low Lights
    mode: queued
    sequence:
      - action: multicast_exec.toggle
        data:
          entity_id:
            - switch.living_room_corner_lamp
            - switch.living_room_bookshelf_lamp
            - light.island_lights
      - action: multicast_exec.set
        data:
          target_state: false
          entity_id:
            - light.living_room_lights
            - light.sink_lights_2
            - light.kitchen_lights
            - light.dining_table_lights


  first_floor_all_on:
    alias: First Floor All On
    description: Turn all of the first floor lights on
    mode: queued
    sequence:
      - action: multicast_exec.set
        data:
          target_state: true
          entity_id:
            - switch.living_room_corner_lamp
            - switch.living_room_bookshelf_lamp
            - light.living_room_lights
            - switch.under_cabinet_lights
            - light.island_lights
            - light.sink_lights_2
            - light.kitchen_lights
            - light.dining_table_lights

  first_floor_all_off:
    alias: First Floor Evening Off
    description: Turn all of the first floor off in the evening
    mode: queued
    sequence:
      - action: multicast_exec.set
        data:
          target_state: false
          entity_id:
            - switch.living_room_corner_lamp
            - switch.living_room_bookshelf_lamp
            - light.living_room_lights
            - light.island_lights
            - light.sink_lights_2
            - light.kitchen_lights
            - light.dining_table_lights


automation:
  - id: set_day_temp
    alias: Set Day Temp
    trigger:
      - platform: time
        at: "08:00"
    action:
      - action: climate.set_temperature
        target:
          entity_id: climate.thermostat
        data:
          target_temp_high: 75
          target_temp_low: 70

  - id: set_transition_temp
    alias: Set Transition Temp
    trigger:
      - platform: time
        at:
          - "07:00"
          - "22:00"
    action:
      - action: climate.set_temperature
        target:
          entity_id: climate.thermostat
        data:
          target_temp_high: 74
          target_temp_low: 69

  - id: set_night_temp
    alias: Set Day Temp
    trigger:
      - platform: time
        at: "23:00"
    action:
      - action: climate.set_temperature
        target:
          entity_id: climate.thermostat
        data:
          target_temp_high: 73
          target_temp_low: 68

  - id: turn_off_master_bedroom_apple_tv
    alias: Turn off Apple TVs
    trigger:
      - platform: time
        at:
          - "00:00"
          - "01:00"
          - "02:00"
          - "03:00"
          - "04:00"
          - "05:00"
    action:
      - action: media_player.turn_off
        target:
          entity_id:
            - media_player.master_bedroom

  - id: turn_off_living_room_apple_tv
    alias: Turn off Apple TVs
    trigger:
      - platform: time
        at:
          - "00:00"
          - "01:00"
          - "02:00"
          - "03:00"
          - "04:00"
          - "05:00"
    action:
      - action: media_player.turn_off
        target:
          entity_id:
            - media_player.living_room

  - id: turn_on_espresso_machine
    alias: Turn on Espresso Machine
    trigger:
      - platform: time
        at: "06:00"
    action:
      - action: switch.turn_on
        target:
          entity_id: switch.espresso_machine

  - id: turn_off_espresso_machine
    alias: Turn off Espresso Machine
    trigger:
      - platform: time
        at:
          - "19:00"
          - "00:00"
    action:
      - action: switch.turn_off
        target:
          entity_id: switch.espresso_machine

  - id: turn_on_mbr_lamp_at_sunset
    alias: "MBR Lamp: On at sunset"
    description: "Turn on the master bedroom lamp at sunset"
    mode: single
    trigger:
      - platform: sun
        event: sunset
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.mbr_lamp

  - id: pico_living_room_1
    alias: Living Room Pico 2 Handler
    trigger:
      - platform: event
        event_type: lutron_caseta_button_event
        event_data:
          area_name: Living Room
          device_name: Living Room 1
          action: press
    action:
      - variables:
          button: "{{trigger.event.data.button_number}}"
          device: "{{trigger.event.data.device_name}}"
          buttons: { top: 2, middle: 3, bottom: 4, up: 5, down: 6 }
      - choose:
          - conditions: "{{button == buttons.bottom}}"
            sequence:
              - action: switch.toggle
                entity_id: switch.living_room_bookshelf_lamp

  - id: pico_living_room_2
    alias: Living Room Pico 2 Handler
    trigger:
      - platform: event
        event_type: lutron_caseta_button_event
        event_data:
          area_name: Living Room
          device_name: Living Room 2
          action: press
    action:
      - variables:
          button: "{{trigger.event.data.button_number}}"
          device: "{{trigger.event.data.device_name}}"
          buttons: { top: 2, middle: 3, bottom: 4, up: 5, down: 6 }
      - choose:
          - conditions: "{{button == buttons.bottom}}"
            sequence:
              - action: script.first_floor_low_lights_toggle

  - id: pico_master_bedroom
    alias: Master Bedroom Pico Handler
    trigger:
      - platform: event
        event_type: lutron_caseta_button_event
        event_data:
          area_name: Master Bedroom
          device_name: Master Bedroom
          action: press
    action:
      - variables:
          button: "{{trigger.event.data.button_number}}"
          device: "{{trigger.event.data.device_name}}"
          buttons: { top: 2, middle: 3, bottom: 4, up: 5, down: 6 }
      - choose:
          - conditions: "{{button == buttons.bottom}}" # Bottom Button
            sequence:
              - action: switch.toggle
                data:
                  entity_id: switch.mbr_lamp

  - id: living_room_lights_scenes
    alias: Living Room Lights Scenes
    trigger:
      - platform: event
        event_type: zwave_js_value_notification
        event_data:
          command_class_name: Central Scene
          device_id: a5c1c236b6340ae8db83857c10e1bd8e
    action:
      - variables:
          direction: "{{'up' if trigger.event.data.property_key == '001' else 'down'}}"
          count: "{{trigger.event.data.value_raw - 1}}"

      - choose:
          - conditions: "{{direction == 'up' and count == 2}}"
            sequence:
              - action: script.first_floor_low_lights_on

          - conditions: "{{direction == 'up' and count == 3}}"
            sequence:
              - action: script.first_floor_all_on

          - conditions: "{{direction == 'down' and count == 2}}"
            sequence:
              - action: script.first_floor_all_off
