logger:
  default:  "info"

sun:
# Enable Apple TV
zeroconf:
dhcp:
# Enable mobile application
mobile_app:
# Enable state history
history:

# Run on localhost, proxying through nginx
http:
  server_host: 127.0.0.1

script:
  entities_toggle:
    alias: Toggle Entities
    description: Toggle a group of entities
    mode: parallel
    fields:
      entity_id:
        description: List of entity IDs
        example: '["light.living_room", "switch.fan"]'
        required: true
        selector:
          entity:
            multiple: true
    sequence:
      - variables:
          any_on: "{{ 'on' in entity_id | map('states') }}"
      - action: "{{ 'homeassistant.turn_off' if any_on else 'homeassistant.turn_on' }}"
        target:
          entity_id: "{{ entity_id }}"

  multicast_switch_set:
    alias: Multicast Switch Set
    description: Set a state for a Group of ZWave switches via multicast
    mode: parallel
    fields:
      entity_id:
        description: List of ZWave entity IDs
        required: True
        selector:
          entity:
            multiple: true
            filter:
              domain: switch
              integration: zwave
      value:
        description: State to set
        required: True
        selector:
          boolean:
    sequence:
      - action: zwave_js.multicast_set_value
        target:
          entity_id: "{{ entity_id }}"
        data:
          command_class: "37"
          property: targetValue
          value: "{{ value }}"

  multicast_switch_toggle:
    alias: Multicast Switch Toggle
    description: Toggle a group of zwave switches via multicast
    mode: parallel
    fields:
      entity_id:
        description: List of ZWave entity IDs
        required: True
        selector:
          entity:
            multiple: true
            filter:
              domain: switch
              integration: zwave
    sequence:
      - action: script.multicast_switch_set
        target:
          entity_id: "{{ entity_id }}"
        data:
          value: "{{ 'on' not in entity_id | map('states') }}"

  multicast_light_set:
    alias: Multicast Light On
    description: Turn on a Group of ZWave lights via multicast
    mode: parallel
    fields:
      entity_id:
        description: List of ZWave entity IDs
        required: True
        selector:
          entity:
            multiple: true
            filter:
              domain: light
              integration: zwave
      value:
        description: Brightness to set for light group
        selector:
          number:
            min: 0
            max: 99
            step: 1
    sequence:
      - action: zwave_js.multicast_set_value
        target:
          entity_id: "{{ entity_id }}"
        data:
          command_class: "38"
          property: targetValue
          value: "{{ value }}"

  multicast_light_toggle:
    alias: Multicast Light Toggle
    description: Toggle a group of zwave lights via multicast
    mode: parallel
    fields:
      entity_id:
        description: List of ZWave entity IDs
        required: True
        selector:
          entity:
            multiple: true
            filter:
              domain: light
              integration: zwave
    sequence:
      - action: script.multicast_light_set
        target:
          entity_id: "{{ entity_id }}"
        data:
          value: "{{ 0 if 'on' in entity_id | map('states') else 99 }}"

  living_room_low_lights_off:
    alias: Living Room Lights Off
    description: Turn off small side lamps in living room
    mode: queued
    sequence:
      - action: script.multicast_switch_set
        target:
          entity_id:
            - switch.living_room_corner_lamp
            - switch.living_room_bookshelf_lamp
        data:
          value: false

  living_room_low_lights_on:
    alias: Living Room Lights On
    description: Turn on small side lamps in living room
    mode: queued
    sequence:
      - action: script.multicast_switch_set
        target:
          entity_id:
            - switch.living_room_corner_lamp
            - switch.living_room_bookshelf_lamp
        data:
          value: true

  living_room_low_lights_toggle:
    alias: Living Room Lights Toggle
    description: Toggle small side lamps in living room
    mode: queued
    sequence:
      - action: script.multicast_switch_toggle
        target:
          entity_id:
            - switch.living_room_corner_lamp
            - switch.living_room_bookshelf_lamp

  kitchen_low_lights_off:
    alias: Kitchen Lights Off
    description: Turn off lower lights in kitchen
    mode: queued
    sequence:
      - action: homeassistant.turn_off
        target:
          entity_id:
            - switch.under_cabinet_lights
            - light.island_lights

  kitchen_low_lights_on:
    alias: Kitchen Lights On
    description: Turn on lower lights in kitchen
    mode: queued
    sequence:
      - action: homeassistant.turn_on
        target:
          entity_id:
            - switch.under_cabinet_lights
            - light.island_lights

  kitchen_low_lights_toggle:
    alias: Kitchen Lights Toggle
    description: Toggle lower level lights in kitchen
    mode: queued
    sequence:
      - action: script.entities_toggle
        target:
          entity_id:
            - switch.under_cabinet_lights
            - light.island_lights

  ceiling_lights_off:
    alias: Ceiling Lights Off
    description: Turn Off First Floor Ceiling Lights
    mode: queued
    sequence:
      - action: script.multicast_light_set
        target:
          entity_id:
            - light.living_room_lights
            - light.sink_lights_2
            - light.kitchen_lights
            - light.dining_table_lights
        data:
          value: 0

  ceiling_lights_on:
    alias: Ceiling Lights On
    description: Turn On First Floor Ceiling Lights
    mode: queued
    sequence:
      - action: script.multicast_light_set
        target:
          entity_id:
            - light.living_room_lights
            - light.sink_lights_2
            - light.kitchen_lights
            - light.dining_table_lights
        data:
          value: 99

  ceiling_lights_toggle:
    alias: Ceiling Lights Toggle
    description: Toggle First Floor Ceiling Lights
    mode: queued
    sequence:
      - action: script.multicast_light_toggle
        target:
          entity_id:
            - light.living_room_lights
            - light.sink_lights_2
            - light.kitchen_lights
            - light.dining_table_lights

  first_floor_morning_on:
    alais: First Floor Morning On
    description: Turn all of the first floor on in the morning
    mode: queued
    sequence:
      - action: script.multicast_switch_set
        target:
          entity_id:
            - switch.living_room_corner_lamp
            - switch.living_room_bookshelf_lamp
            - switch.under_cabinet_lights
        data:
          value: true

      - action: script.multicast_light_set
        target:
            - light.island_lights
            - light.living_room_lights
            - light.sink_lights_2
            - light.kitchen_lights
            - light.dining_table_lights
        data:
          value: 99

  first_floor_evening_off:
    alais: First Floor Evening Off
    description: Turn all of the first floor off in the evening
    mode: queued
    sequence:
      - action: script.multicast_switch_set
        target:
          entity_id:
            - switch.living_room_corner_lamp
            - switch.living_room_bookshelf_lamp
        data:
          value: false

      - action: script.multicast_light_set
        target:
            - light.island_lights
            - light.living_room_lights
            - light.sink_lights_2
            - light.kitchen_lights
            - light.dining_table_lights
        data:
          value: 0


automation:
  - id: set_day_temp
    alias: Set Day Temp
    trigger:
      - platform: time
        at: "08:00"
    action:
      - action: climate.set_temperature
        target:
          entity_id: climate.thermostat
        data:
          target_temp_high: 75
          target_temp_low: 70

  - id: set_transition_temp
    alias: Set Transition Temp
    trigger:
      - platform: time
        at: "07:00"
      - platform: time
        at: "22:30"
    action:
      - action: climate.set_temperature
        target:
          entity_id: climate.thermostat
        data:
          target_temp_high: 74
          target_temp_low: 69

  - id: set_night_temp
    alias: Set Day Temp
    trigger:
      - platform: time
        at: "08:00"
    action:
      - action: climate.set_temperature
        target:
          entity_id: climate.thermostat
        data:
          target_temp_high: 73
          target_temp_low: 68


  - id: turn_off_master_bedroom_apple_tv
    alias: Turn off Apple TVs
    trigger:
      - platform: time
        at: "01:00:00"
      - platform: time
        at: "02:00:00"
    action:
      - action: media_player.turn_off
        target:
          entity_id:
            - media_player.master_bedroom

  - id: turn_off_living_room_apple_tv
    alias: Turn off Apple TVs
    trigger:
      - platform: time
        at: "01:00:00"
      - platform: time
        at: "02:00:00"
    action:
      - action: media_player.turn_off
        target:
          entity_id:
            - media_player.living_room

  - id: turn_on_espresso_machine
    alias: Turn on Espresso Machine
    trigger:
      - platform: time
        at: "07:30:00"
    action:
      - action: switch.turn_on
        target:
          entity_id: switch.espresso_machine

  - id: turn_off_espresso_machine
    alias: Turn off Espresso Machine
    trigger:
      - platform: time
        at: "19:00:00"
    action:
      - action: switch.turn_off
        target:
          entity_id: switch.espresso_machine

  - id: pico_living_room_1
    alias: Living Room Pico 1 Handler
    trigger:
      - platform: event
        event_type: lutron_caseta_button_event
        event_data:
          area_name: Living Room
          device_name: Living Room 1
          action: press
    action:
      - variables:
          button: "{{trigger.event.data.button_number}}"
          device: "{{trigger.event.data.device_name}}"
      - choose:
          - conditions: "{{button == 2}}" # Top Button
            sequence:
              - action: system_log.write
                data:
                  message: "Pico {{device}} Top Button Pressed!"
                  level: debug
          - conditions: "{{button == 4}}" # Bottom Button
            sequence:
              - action: switch.toggle
                data:
                  entity_id: switch.living_room_corner_lamp
          - conditions: "{{button == 5}}" # Up Arrow
            sequence:
              - action: system_log.write
                data:
                  message: "Pico {{device}} Up Arrow Pressed!"
                  level: debug
          - conditions: "{{button == 3}}" # Middle Button
            sequence:
              - action: system_log.write
                data:
                  message: "Pico {{device}} Middle Button Pressed!"
                  level: debug
          - conditions: "{{button == 6}}" # Bottom Arrow
            sequence:
              - action: system_log.write
                data:
                  message: "Pico {{device}} Bottom Arrow Pressed!"
                  level: debug

  - id: pico_living_room_2
    alias: Living Room Pico 2 Handler
    trigger:
      - platform: event
        event_type: lutron_caseta_button_event
        event_data:
          area_name: Living Room
          device_name: Living Room 2
          action: press
    action:
      - variables:
          button: "{{trigger.event.data.button_number}}"
          device: "{{trigger.event.data.device_name}}"
      - choose:
          - conditions: "{{button == 2}}" # Top Button
            sequence:
              - action: system_log.write
                data:
                  message: "Pico {{device}} Top Button Pressed!"
                  level: debug
          - conditions: "{{button == 4}}" # Bottom Button
            sequence:
              - action: switch.toggle
                data:
                  entity_id: switch.living_room_bookshelf_lamp
          - conditions: "{{button == 5}}" # Up Arrow
            sequence:
              - action: system_log.write
                data:
                  message: "Pico {{device}} Up Arrow Pressed!"
                  level: debug
          - conditions: "{{button == 3}}" # Middle Button
            sequence:
              - action: system_log.write
                data:
                  message: "Pico {{device}} Middle Button Pressed!"
                  level: debug
          - conditions: "{{button == 6}}" # Bottom Arrow
            sequence:
              - action: system_log.write
                data:
                  message: "Pico {{device}} Bottom Arrow Pressed!"
                  level: debug

  - id: pico_master_bedroom
    alias: Master Bedroom Pico Handler
    trigger:
      - platform: event
        event_type: lutron_caseta_button_event
        event_data:
          area_name: Master Bedroom
          device_name: Master Bedroom
          action: press
    action:
      - variables:
          button: "{{trigger.event.data.button_number}}"
          device: "{{trigger.event.data.device_name}}"
      - choose:
          - conditions: "{{button == 2}}" # Top Button
            sequence:
              - action: system_log.write
                data:
                  message: "Pico {{device}} Top Button Pressed!"
                  level: debug
          - conditions: "{{button == 4}}" # Bottom Button
            sequence:
              - action: switch.toggle
                data:
                  entity_id: switch.mbr_lamp
          - conditions: "{{button == 5}}" # Up Arrow
            sequence:
              - action: system_log.write
                data:
                  message: "Pico {{device}} Up Arrow Pressed!"
                  level: debug
          - conditions: "{{button == 3}}" # Middle Button
            sequence:
              - action: system_log.write
                data:
                  message: "Pico {{device}} Middle Button Pressed!"
                  level: debug
          - conditions: "{{button == 6}}" # Bottom Arrow
            sequence:
              - action: system_log.write
                data:
                  message: "Pico {{device}} Bottom Arrow Pressed!"
                  level: debug

  - id: living_room_lights_scenes
    alias: Living Room Lights Scenes
    trigger:
      - platform: event
        event_type: zwave_js_value_notification
        event_data:
          command_class_name: Central Scene
          device_id: a5c1c236b6340ae8db83857c10e1bd8e
    action:
      - variables:
          direction: "{{'up' if trigger.event.data.property_key == '001' else 'down'}}"
          count: "{{trigger.event.data.value_raw - 1}}"

      - conditions: "{{direction == 'up' and count == 2}}"
        sequence:
          - action: script.first_floor_morning_on

      - conditions: "{{direction == 'down' and count == 2}}"
        sequence:
          - action: script.first_floor_evening_off
