logger:
  default:  "info"

sun:
zeroconf:
dhcp:
mobile_app:

http:
  server_host: 127.0.0.1

script:
  toggle_entities:
    alias: Toggle Entities
    description: Toggle a group of entities
    mode: queued
    fields:
      entity_id:
        description: List of entity IDs
        example: '["light.living_room", "switch.fan"]'
        required: true
        selector:
          entity:
            multiple: true
    sequence:
      - variables:
          any_on: "{{ 'on' in entity_id | map('states') }}"
      - service: "{{ 'homeassistant.turn_off' if any_on else 'homeassistant.turn_on' }}"
        target:
          entity_id: "{{ entity_id }}"

  # living_room_low_lights_off:
  # living_room_low_lights_on:
  # living_room_low_lights_toggle:

  # kitchen_low_lights_off:
  # kitchen_low_lights_on:
  # kitchen_low_lights_toggle:

  # ceiling_lights_off:
  # ceiling_lights_on:
  # ceiling_lights_on_33:
  # ceiling_lights_on_66:
  # ceiling_lights_on_100:
  # ceiling_lights_toggle:


automation:
  - id: set_day_temp
    alias: Set Day Temp
    trigger:
      - platform: time
        at: "08:00"
    action:
      - action: climate.set_temperature
        target:
          entity_id: climate.thermostat
        data:
          target_temp_high: 75
          target_temp_low: 70

  - id: set_transition_temp
    alias: Set Transition Temp
    trigger:
      - platform: time
        at: "07:00"
      - platform: time
        at: "22:30"
    action:
      - action: climate.set_temperature
        target:
          entity_id: climate.thermostat
        data:
          target_temp_high: 74
          target_temp_low: 69

  - id: set_night_temp
    alias: Set Day Temp
    trigger:
      - platform: time
        at: "08:00"
    action:
      - action: climate.set_temperature
        target:
          entity_id: climate.thermostat
        data:
          target_temp_high: 73
          target_temp_low: 68


  - id: turn_off_master_bedroom_apple_tv
    alias: Turn off Apple TVs
    trigger:
      - platform: time
        at: "01:00:00"
      - platform: time
        at: "02:00:00"
    action:
      - service: media_player.turn_off
        target:
          entity_id:
            - media_player.master_bedroom

  - id: turn_off_living_room_apple_tv
    alias: Turn off Apple TVs
    trigger:
      - platform: time
        at: "01:00:00"
      - platform: time
        at: "02:00:00"
    action:
      - service: media_player.turn_off
        target:
          entity_id:
            - media_player.living_room

  - id: turn_on_espresso_machine
    alias: Turn on Espresso Machine
    trigger:
      - platform: time
        at: "07:30:00"
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.espresso_machine

  - id: turn_off_espresso_machine
    alias: Turn off Espresso Machine
    trigger:
      - platform: time
        at: "19:00:00"
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.espresso_machine

  - id: pico_living_room_1
    alias: Living Room Pico 1 Handler
    trigger:
      - platform: event
        event_type: lutron_caseta_button_event
        event_data:
          area_name: Living Room
          device_name: Living Room 1
          action: press
    action:
      - variables:
          button: "{{trigger.event.data.button_number}}"
          device: "{{trigger.event.data.device_name}}"
      - choose:
          - conditions: "{{button == 2}}" # Top Button
            sequence:
              - action: system_log.write
                data:
                  message: "Pico {{device}} Top Button Pressed!"
                  level: debug
          - conditions: "{{button == 4}}" # Bottom Button
            sequence:
              - service: switch.toggle
                data:
                  entity_id: switch.living_room_corner_lamp
          - conditions: "{{button == 5}}" # Up Arrow
            sequence:
              - action: system_log.write
                data:
                  message: "Pico {{device}} Up Arrow Pressed!"
                  level: debug
          - conditions: "{{button == 3}}" # Middle Button
            sequence:
              - action: system_log.write
                data:
                  message: "Pico {{device}} Middle Button Pressed!"
                  level: debug
          - conditions: "{{button == 6}}" # Bottom Arrow
            sequence:
              - action: system_log.write
                data:
                  message: "Pico {{device}} Bottom Arrow Pressed!"
                  level: debug

  - id: pico_living_room_2
    alias: Living Room Pico 2 Handler
    trigger:
      - platform: event
        event_type: lutron_caseta_button_event
        event_data:
          area_name: Living Room
          device_name: Living Room 2
          action: press
    action:
      - variables:
          button: "{{trigger.event.data.button_number}}"
          device: "{{trigger.event.data.device_name}}"
      - choose:
          - conditions: "{{button == 2}}" # Top Button
            sequence:
              - action: system_log.write
                data:
                  message: "Pico {{device}} Top Button Pressed!"
                  level: debug
          - conditions: "{{button == 4}}" # Bottom Button
            sequence:
              - service: switch.toggle
                data:
                  entity_id: switch.living_room_bookshelf_lamp
          - conditions: "{{button == 5}}" # Up Arrow
            sequence:
              - action: system_log.write
                data:
                  message: "Pico {{device}} Up Arrow Pressed!"
                  level: debug
          - conditions: "{{button == 3}}" # Middle Button
            sequence:
              - action: system_log.write
                data:
                  message: "Pico {{device}} Middle Button Pressed!"
                  level: debug
          - conditions: "{{button == 6}}" # Bottom Arrow
            sequence:
              - action: system_log.write
                data:
                  message: "Pico {{device}} Bottom Arrow Pressed!"
                  level: debug

  - id: pico_master_bedroom
    alias: Master Bedroom Pico Handler
    trigger:
      - platform: event
        event_type: lutron_caseta_button_event
        event_data:
          area_name: Master Bedroom
          device_name: Master Bedroom
          action: press
    action:
      - variables:
          button: "{{trigger.event.data.button_number}}"
          device: "{{trigger.event.data.device_name}}"
      - choose:
          - conditions: "{{button == 2}}" # Top Button
            sequence:
              - action: system_log.write
                data:
                  message: "Pico {{device}} Top Button Pressed!"
                  level: debug
          - conditions: "{{button == 4}}" # Bottom Button
            sequence:
              - service: switch.toggle
                data:
                  entity_id: switch.mbr_lamp
          - conditions: "{{button == 5}}" # Up Arrow
            sequence:
              - action: system_log.write
                data:
                  message: "Pico {{device}} Up Arrow Pressed!"
                  level: debug
          - conditions: "{{button == 3}}" # Middle Button
            sequence:
              - action: system_log.write
                data:
                  message: "Pico {{device}} Middle Button Pressed!"
                  level: debug
          - conditions: "{{button == 6}}" # Bottom Arrow
            sequence:
              - action: system_log.write
                data:
                  message: "Pico {{device}} Bottom Arrow Pressed!"
                  level: debug
