[tool.poetry]
name = "iterm-cfg"
version = "0.1.0"
description = ""
authors = ["Matthew Mazzanti <matthew.mazzanti@gmail.com>"]
readme = "README.md"
packages = [{include = "iterm_cfg"}]

[tool.poetry.dependencies]
python = "^3.10"
iterm2 = "^2.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
