# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "rpool/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "rpool/nix";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "rpool/home";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/ADE8-1393";
      fsType = "vfat";
    };

  fileSystems."/var/lib/plex" =
    { device = "ppool/plex";
      fsType = "zfs";
    };

  fileSystems."/var/lib/gitea" =
    { device = "dpool/git";
      fsType = "zfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/9949757f-f780-453c-b952-97ee10541a9b"; }
    ];

}
